#!/usr/bin/env python
# encoding: utf-8


def build(bld):
	obj = bld.program(features = 'cxx',
                          source = 'mono_dim.cpp',
                          includes = '. .. ../../',
                          target = 'mono_dim',
                          uselib =  'BOOST EIGEN TBB',
                          use = 'limbo')
	obj = bld.program(features = 'cxx',
                          source = 'parego.cpp',
                          includes = '. .. ../../',
                          target = 'parego',
                          uselib =  'BOOST EIGEN TBB SFERES',
                          use = 'limbo')
