#!/usr/bin/env python
# encoding: utf-8


def build(bld):
    obj = bld.program(features='cxx',
                      source='mono_dim.cpp',
                      includes='. .. ../../',
                      target='mono_dim',
                      uselib='BOOST EIGEN TBB LIBCMAES NLOPT',
                      use='limbo')
    obj = bld.program(features='cxx',
                      source='obs_multi.cpp',
                      includes='. .. ../../',
                      target='obs_multi',
                      uselib='BOOST EIGEN TBB LIBCMAES NLOPT',
                      use='limbo')
    obj = bld.program(features='cxx',
                      source='obs_multi_auto_mean.cpp',
                      includes='. .. ../../',
                      target='obs_multi_auto_mean',
                      uselib='BOOST EIGEN TBB LIBCMAES NLOPT',
                      use='limbo')

    if bld.options.experimental:
            bld.recurse('experimental/')
