#!/usr/bin/env python
# encoding: utf-8


def build(bld):
    bld.recurse('examples')
    if bld.options.tests:
        bld.recurse('tests')
    bld.recurse('benchmarks')

    bld.stlib(source=' \
              ehvi/ehvi_calculations.cc \
              ehvi/ehvi_montecarlo.cc \
              ehvi/ehvi_sliceupdate.cc \
              ehvi/ehvi_hvol.cc \
              ehvi/ehvi_multi.cc \
              ehvi/helper.cc \
              hv/hypervol.c',
              target='limbo')


def build_extensive_tests(bld):
    bld.stlib(source=' \
              ehvi/ehvi_calculations.cc \
              ehvi/ehvi_montecarlo.cc \
              ehvi/ehvi_sliceupdate.cc \
              ehvi/ehvi_hvol.cc \
              ehvi/ehvi_multi.cc \
              ehvi/helper.cc \
              hv/hypervol.c',
              target='limbo')
